var soundData =
    {
        '0': './sounds/0.mp3',
        '1': './sounds/1.mp3',
        '2': './sounds/2.mp3',
        '3': './sounds/3.mp3',
        '4': './sounds/4.mp3',
        '5': './sounds/5.mp3',
        '6': './sounds/6.mp3',
        '7': './sounds/7.mp3',
        '8': './sounds/8.mp3',
        '9': './sounds/9.mp3',
        A: './sounds/A.mp3',
        Alt: './sounds/Alt.mp3',
        Ampersand: './sounds/Ampersand.mp3',
        'Arrow Down': './sounds/Arrow Down.mp3',
        'Arrow Left': './sounds/Arrow Left.mp3',
        'Arrow Right': './sounds/Arrow Right.mp3',
        'Arrow Up': './sounds/Arrow Up.mp3',
        Asterisk: './sounds/Asterisk.mp3',
        At: './sounds/At.mp3',
        B: './sounds/B.mp3',
        Backslash: './sounds/Backslash.mp3',
        Backspace: './sounds/Backspace.mp3',
        Backtick: './sounds/Backtick.mp3',
        C: './sounds/C.mp3',
        'Caps Lock': './sounds/Caps Lock.mp3',
        Caret: './sounds/Caret.mp3',
        Colon: './sounds/Colon.mp3',
        Comma: './sounds/Comma.mp3',
        Control: './sounds/Control.mp3',
        D: './sounds/D.mp3',
        Delete: './sounds/Delete.mp3',
        Ding: './sounds/Ding.mp3',
        Dollar: './sounds/Dollar.mp3',
        'Double Quote': './sounds/Double Quote.mp3',
        E: './sounds/E.mp3',
        End: './sounds/End.mp3',
        Enter: './sounds/Enter.mp3',
        Equals: './sounds/Equals.mp3',
        Escape: './sounds/Escape.mp3',
        'Exclamation Point': './sounds/Exclamation Point.mp3',
        F: './sounds/F.mp3',
        F1: './sounds/F1.mp3',
        F10: './sounds/F10.mp3',
        F11: './sounds/F11.mp3',
        F12: './sounds/F12.mp3',
        F2: './sounds/F2.mp3',
        F3: './sounds/F3.mp3',
        F4: './sounds/F4.mp3',
        F5: './sounds/F5.mp3',
        F6: './sounds/F6.mp3',
        F7: './sounds/F7.mp3',
        F8: './sounds/F8.mp3',
        F9: './sounds/F9.mp3',
        'Forward Slash': './sounds/Forward Slash.mp3',
        Function: './sounds/Function.mp3',
        G: './sounds/G.mp3',
        'Greater Than': './sounds/Greater Than.mp3',
        H: './sounds/H.mp3',
        Hash: './sounds/Hash.mp3',
        Home: './sounds/Home.mp3',
        Hyphen: './sounds/Hyphen.mp3',
        I: './sounds/I.mp3',
        Insert: './sounds/Insert.mp3',
        J: './sounds/J.mp3',
        K: './sounds/K.mp3',
        L: './sounds/L.mp3',
        'Left Bracket': './sounds/Left Bracket.mp3',
        'Left Curly Bracket': './sounds/Left Curly Bracket.mp3',
        'Left Paren': './sounds/Left Paren.mp3',
        'Less Than': './sounds/Less Than.mp3',
        M: './sounds/M.mp3',
        Meta: './sounds/Meta.mp3',
        N: './sounds/N.mp3',
        No: './sounds/No.mp3',
        'Num Lock': './sounds/Num Lock.mp3',
        O: './sounds/O.mp3',
        P: './sounds/P.mp3',
        'Page Down': './sounds/Page Down.mp3',
        'Page Up': './sounds/Page Up.mp3',
        Pause: './sounds/Pause.mp3',
        Percent: './sounds/Percent.mp3',
        Period: './sounds/Period.mp3',
        Pipe: './sounds/Pipe.mp3',
        Plus: './sounds/Plus.mp3',
        Pound: './sounds/Pound.mp3',
        'Print Screen': './sounds/Print Screen.mp3',
        Q: './sounds/Q.mp3',
        'Question Mark': './sounds/Question Mark.mp3',
        R: './sounds/R.mp3',
        'Right Bracket': './sounds/Right Bracket.mp3',
        'Right Curly Bracket': './sounds/Right Curly Bracket.mp3',
        'Right Paren': './sounds/Right Paren.mp3',
        S: './sounds/S.mp3',
        Semicolon: './sounds/Semicolon.mp3',
        Shift: './sounds/Shift.mp3',
        'Single Quote': './sounds/Single Quote.mp3',
        Slash: './sounds/Slash.mp3',
        Space: './sounds/Space.mp3',
        'Stop Aurora': './sounds/Stop Aurora.mp3',
        'Stop moving x3': './sounds/Stop moving x3.mp3',
        'Stop moving': './sounds/Stop moving.mp3',
        T: './sounds/T.mp3',
        Tab: './sounds/Tab.mp3',
        Tada: './sounds/Tada.mp3',
        Tilde: './sounds/Tilde.mp3',
        U: './sounds/U.mp3',
        Underscore: './sounds/Underscore.mp3',
        V: './sounds/V.mp3',
        W: './sounds/W.mp3',
        Windows: './sounds/Windows.mp3',
        X: './sounds/X.mp3',
        Y: './sounds/Y.mp3',
        Yay: './sounds/Yay.mp3',
        Z: './sounds/Z.mp3'
    };
